name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 * * * *" # Update every hour
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Update README
        uses: anmol098/waka-readme-stats@master
        env:
          GH_TOKEN: ${{ secrets.ghStatsToken }}
        with: